In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot

In [8]:
x=np.arange(1,15,+2)
print(x)

[ 1  3  5  7  9 11 13]


In [18]:
y=[12,10,8,6,4]
y.append(2)
y.append(0)
print(len(y))
print(type(y))
print(y)
y=np.asarray(y)
print(len(y))
print(type(y))
print(y)

7
<class 'list'>
[12, 10, 8, 6, 4, 2, 0]
7
<class 'numpy.ndarray'>
[12 10  8  6  4  2  0]


In [6]:
y.size

5

In [7]:
x.size

7

In [20]:
print(x)
print(y)
x+y

[ 1  3  5  7  9 11 13]
[12 10  8  6  4  2  0]


array([13, 13, 13, 13, 13, 13, 13])

In [21]:
x*y

array([12, 30, 40, 42, 36, 22,  0])

In [22]:
x-y

array([-11,  -7,  -3,   1,   5,   9,  13])

In [23]:
x/y

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([0.08333333, 0.3       , 0.625     , 1.16666667, 2.25      ,
       5.5       ,        inf])

In [0]:
x=np.reshape(x,(7,1))

In [0]:
y=np.reshape(y,(1,7))

In [29]:
x.shape

(7, 1)

In [30]:
y.shape

(1, 7)

In [31]:
x*y

array([[ 12,  10,   8,   6,   4,   2,   0],
       [ 36,  30,  24,  18,  12,   6,   0],
       [ 60,  50,  40,  30,  20,  10,   0],
       [ 84,  70,  56,  42,  28,  14,   0],
       [108,  90,  72,  54,  36,  18,   0],
       [132, 110,  88,  66,  44,  22,   0],
       [156, 130, 104,  78,  52,  26,   0]])

In [35]:
a1=np.arange(50).reshape(2,5,5)
a1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [36]:
print(x)
y

[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]]


array([[12, 10,  8,  6,  4,  2,  0]])

In [37]:
x.dot(y)

array([[ 12,  10,   8,   6,   4,   2,   0],
       [ 36,  30,  24,  18,  12,   6,   0],
       [ 60,  50,  40,  30,  20,  10,   0],
       [ 84,  70,  56,  42,  28,  14,   0],
       [108,  90,  72,  54,  36,  18,   0],
       [132, 110,  88,  66,  44,  22,   0],
       [156, 130, 104,  78,  52,  26,   0]])